### ISSUE TITLE
Multiple sources

### ISSUE THREAD

**Issue by martinRenou** [ifl0w/RandomWallpaperGnome3#102]
Hello there :) Happy to see the extension works great with Gnome 40

It would be great if one could use different sources for fetching the backgrounds (especially if local folders gets supported #87), and sources would be randomly picked before fetching a random wallpaper.

I'd be happy to provide help. Although I would need some pointers.

**Comment by ifl0w** [comment]
Hello! :) 

The decision on which source is used is basically done here in [_requestRandomImageFromAdapter(..)](https://github.com/ifl0w/RandomWallpaperGnome3/blob/2fac0b0bd83ee01a5352a3bec4a806136e5b8f8d/randomwallpaper%40iflow.space/wallpaperController.js#L86). You could put your own logic there for your personal use but for the general public a UI would be required.

Developing and wiring up the UI unfortunately is more time-consuming. The UI elements for the settings have to be defined in "settings.ui" which has to be done manually since GTK Builder currently does not support GTK 4. The gschema has to be adapted so that all necessary values can be stored persistently. Next, the UI elements and the gschema have to be connected in "prefs.js". Finally, you can access the settings in the app and configure the settings via the UI.

Probably, the most time-consuming part for me would be to define the UI elements so that it is somewhat usable. If you have experience with GTK (especially GTK4) then I'd be happy for any suggestions. :)

**Comment by martinRenou** [comment]
No experience with GTK here, although this would be a fun side-project for me to learn. I might give it a shot and push a PR :)

**Comment by ifl0w** [comment]
That would be cool! I'd be interested to know what you plan on doing once you begin so that I can better align it with other features. So keep me up to date. :)

**Comment by ifl0w** [comment]
Supported in v3.0.0.
