### ISSUE TITLE
Rate Limit Exceeded for Unsplash

### ISSUE THREAD

**Issue by pascallj** [ifl0w/RandomWallpaperGnome3#108]
At the moment we are exceeding the rate limit for the Unsplash API with our API key.

There are several options I can think of to fix this:
* Wait until we are not exceeding the limit anymore. Possibly along with a restriction on the minimum auto-fetch interval.
* [Apply for a higher rate limit on the API key.](https://help.unsplash.com/en/articles/3887917-when-should-i-apply-for-a-higher-rate-limit)
* Let everyone sign-up as a developer to request their own API keys and enter them in the program.
* Use the [Unsplash Source](https://source.unsplash.com/) 'API' instead of the full-fledged API. Although I cannot find any documentation on how rate limiting is implemented in this API, I assume it is based on IP address.

I don't know how generous Unsplash is with increasing their rate limits. If that is not an issue, then that is obviously the best. 

On our end I think the last option is relatively easy to implement. Specifying multiple collections or using featured images is not possible in the Source API however.

What is the preferred way to proceed?

**Comment by ifl0w** [comment]
Wow, I somehow managed to bury some important mails from Unsplash in my inbox. They changed their pricing model and the API is no longer free. I am not able to pay the fee, since I do not earn any money with this extension.
I just wrote them whether there is some workaround for this project.

However, I suspect that your recommended way of using the "Unsplash Source API" is the best option.
I just finished a basic implementation of it. I'll release it later after going through the most recent PR.

**Comment by pascallj** [comment]
You're welcome. I love this addon.

That's strange, there is no information on their website in that regard. Every piece of information on their website still says it's free. The only article I can find is [this](https://downloadfree.pictures/2021/08/09/unsplash-will-apparently-charge-for-the-use-of-its-api-in-the-near-future/). Just being curious: what did they quote you?

**Comment by pascallj** [comment]
Thank you for your fast fix btw.

Regarding 153f92b: I am no expert in Gnome-shell addons. Is there a way to implement this for 3.38 (Ubuntu 21.04) or 3.36 (Ubuntu 20.04 LTS)? It seems like that this commit also introduces some 3.40 specific code as well?

With this commit I can see new wallpapers from Unsplash Source coming in, but I don't have any settings fields in the sources tab anymore.

**Comment by ifl0w** [comment]
The new pricing took effect on 1. September and they estimated $1K per month for this application... obviously, this is too much to pay for on my own ^^ ... Maybe they come back with an alternative solution but I don't think that there will be a better solution than source.unsplash.com. 
Also, the application key in the source code was really hacky as it should have been private all the time. So I think the new implementation is the best I can do for now. 

I stopped support for older versions since it was a very tedious task to test multiple setups on my own. Hopefully things get better with the new gnome shell 40.
Backporting would certainly be possible but I do not have a running setup with an older gnome version and it still takes some free time to backport everything. The main source of issues is the switch to GTK4 in gnome-shell 40. Basically only the UI has to be rewritten/fixed.

The new settings UI looks something like this:
![Screenshot from 2021-09-03 16-06-08](https://user-images.githubusercontent.com/5549805/132018611-4d6530cc-0b66-4c42-9365-ebf3d0301dc3.png)

In #107 I also suggested removing or backporting Unsplash from older versions entirely. If you have the time and motivation you might want to join the discussion there.

**Comment by pascallj** [comment]
> The new pricing took effect on 1. September and they estimated $1K per month for this application... obviously, this is too much to pay for on my own ^^ ... Maybe they come back with an alternative solution but I don't think that there will be a better solution than source.unsplash.com.

What on earth are they thinking? I can understand the need to make money, but this is outrageous.

> I stopped support for older versions since it was a very tedious task to test multiple setups on my own. Hopefully things get better with the new gnome shell 40.
> Backporting would certainly be possible but I do not have a running setup with an older gnome version and it still takes some free time to backport everything. The main source of issues is the switch to GTK4 in gnome-shell 40. Basically only the UI has to be rewritten/fixed.

I'll add it to my list of projects :wink:. I do think it's worth it as Ubuntu and Debian are definitely the most used distributions and both won't upgrade to more recent versions any time soon.

**Comment by ifl0w** [comment]
> What on earth are they thinking? I can understand the need to make money, but this is outrageous.

Something like 0.5 to 1.0 cents per image. This extension (or at least the application key used) made about 300K requests to their API every month. Tbh these statistics were interesting to me personally, and they are also gone now^^   

> I'll add it to my list of projects wink. I do think it's worth it as Ubuntu and Debian are definitely the most used distributions and both won't upgrade to more recent versions any time soon.

You have a point there, but I'd be more interested in rewriting and refactoring the whole extension than maintaining the legacy code for older versions – it's a little bit of a mess tbh. 
Anyways, it would be really cool to see a contribution from you at some point! :)
