### ISSUE TITLE
[Feature Request] Different wallpapers on multiple display support

### ISSUE THREAD

**Issue by GabLeRoux** [ifl0w/RandomWallpaperGnome3#117]
I don't really know if that's even possible based on gnome's api, but I think some per screen settings would be really nice.

I think this also relates to https://github.com/ifl0w/RandomWallpaperGnome3/pull/107

**Comment by ifl0w** [comment]
Unfortunately, based on the fact that there are no settings for individual displays in the dconf `org.gnome.desktop.background` (which is used for setting the background), I'd assume that this is not really possible. One solution could be to splice images together in a mosaic with the exact resolution of every screen and then stretch the image across all screens. However, this would be a big effort to implement, an ugly workaround, and requires a more complex UI. So I currently don't see a realistic way to add this feature.  

Let me know when you find any sources or software that is capable of achieving the desired effect in an easy way! Until then I'll close the issue since it can't be implemented with reasonable effort.

**Comment by GabLeRoux** [comment]
https://gitlab.com/gabmus/HydraPaper does it (note that it's GNU GPL V3). I did not look at how they're doing it tho.

**Comment by ifl0w** [comment]
Thanks for the input! It looks like they achieve it in the exact way that I described above (which is quite some work). From their Flatpak description: "It accomplishes this by scaling and merging different wallpapers into a single one and setting it as spanned."

I'll reopen this issue for the record of others, but unfortunately, I don't see myself implementing it anytime soon.

**Comment by Lucki** [comment]
The link above is outdated. I was confused I couldn't find my own issues there. The correct project location is https://gitlab.gnome.org/GabMus/HydraPaper

**Comment by ifl0w** [comment]
I guess this is supported in v3.0.0 now. Thus closing this issue.

Hope this feature doesn't regress too quickly because I don't have a multi-monitor setup :sweat_smile: .. Would be a good use case for some automated testing :face_exhaling:
