### ISSUE TITLE
Auto-fetch is downloading multiple images

### ISSUE THREAD

**Issue by flexbarence** [ifl0w/RandomWallpaperGnome3#135]
The extension is downloading two wallpapers, about two minutes apart, every 90 minutes. How can I reset the counter so I only get one wallpaper at a time?

**Comment by ifl0w** [comment]
Thanks for the report! 

I fixed a similar-sounding bug just a few days ago (see #130).  
So, is this also happening with the current version from this repository?

If yes, does it also happen with a shorter interval? Because waiting 90 minutes until the bug appears is kind of unfortunate for debugging. :P

**Comment by flexbarence** [comment]
Dear Wolfgang,

I reset the auto-fetch to 5 minutes, and sure enough, it downloaded two
images, about 5 seconds apart.

Take care,

Barry

**Comment by ifl0w** [comment]
Should be resolved
