### ISSUE TITLE
Extensions.gnome.org installs non-latest version due to version mismatch

### ISSUE THREAD

**Issue by SonnyX** [ifl0w/RandomWallpaperGnome3#14]
One of the earlier versions had in its metadata.json version 4.
That makes it the newest version plus when using the one from github every time opening the browser will give the update plugin message.

**Comment by ifl0w** [comment]
Hello,

the extension has been reviewed just few hours ago. If you are on gnome 3.20 or later than the version 8 should be installed from the extension site. The problem with the version numbers is that they are overwritten by the next integer during the review process. The current version is 8 although I marked the version as "2.1.0".

I do not get any update messages but the ones you do encounter are probably due to the fact that the version from GitHub does not match the version of extensions.gnome.org. We could fix that by using the same version number as extensions.gnome.org but I do not like plain Integers as version numbers since it is much more complicate to follow the development of features and fixes.

Maybe you have another suggestion to solve this issue, otherwise I'd just ignore it since I can not change the versioning of extensions.gnome.org.

**Comment by ifl0w** [comment]
This should be resolved.
