### ISSUE TITLE
New sources of images

### ISSUE THREAD

**Issue by adomo88** [ifl0w/RandomWallpaperGnome3#15]
Hi! Nice work with the extension. In the future maybe you are interested to add more sources to get images, so here are some that are used by Variety as well:

- Flickr, limited to CC-licensed images
- Bing (still under question) – the terms of use there say “Use of this image is restricted to wallpaper only.”, which is the case with Variety

**Comment by ifl0w** [comment]
Hello and thank you! :) 

The Bing source (picture of the day) is definitely the easier one since I don't need to bother with any authentication. The drawback is that you can not request random images. It would be the same image for the whole day. 

I did not take a look at the Flickr API and do not know how complex the implementation would be but I personally favor the Chromcast backgrounds from #9 as the next wallpaper source.

Implementing further sources is currently not the highest priority for me but I appreciate your suggestions.

**Comment by ifl0w** [comment]
You can also join the discussion of #22 if you want to.

**Comment by ifl0w** [comment]
Bing can be realized with the new generic JSON source and Flickr should also be possible, but I did not try that. 

https://github.com/ifl0w/RandomWallpaperGnome3/wiki/Generic-JSON-Source
