### ISSUE TITLE
option to load wallpapers from local folder

### ISSUE THREAD

**Issue by beangoben** [ifl0w/RandomWallpaperGnome3#30]

**Comment by comptekki** [comment]
In the mean time you can install
npm
run 
sudo npm install -g http-server

put your files in a folder
create a .json file like backgrounds.json in chromecats-backgrounds at https://github.com/ifl0w/RandomWallpaperGnome3/wiki/Generic-JSON-Source

cd to the folder and then run 
http-server

in the random wallpaper extension settings select generic json and for the
request url:
http://localhost:8080/backgrounds.json

for
json path:
$[@random].url

and your random wallpapers should work from the local files :)

**Comment by ifl0w** [comment]
Well that's an interesting workaround! ^^
And you need to ensure that the http-server starts during boot.

Thank you for the tip/information! 
I'll try to take a look at a probably fairly simple implementation of this feature.

**Comment by Gordonei** [comment]
Thanks to @ifl0w for this great project! Made the move back from OSX all the easier.

I see people were asking about this feature recently - to shamelessly promote my own project, I created a [little service](https://github.com/Gordonei/wallpaper_server) for wrapping the local file serving behaviour above.

It also has the ability to serve up arbitrary resolutions, through a combination of rescaling and adding a border (for resolutions bigger than the image). Additional feature requests/patches welcome!

**Comment by iMartyn** [comment]
I have taken @Gordonei 's idea and built a similar service, only in go, so it's a bit smaller and streamlined.  Doesn't do the magic scaling stuff or anything fancy, but because of that, it's much smaller.

https://git.martyn.berlin/martyn/wallpaper-server

**Comment by r7l** [comment]
I've tried to write a package for Gentoo for this extension and stumbled across the issue that wallpapers are stored inside the extension directory. This makes it hard to write a useful package at all. I am not a fan of the http server idea or any docker image like others suggested here. On Gentoo people write Ebuilds for Gnome extensions and put extensions to `/usr/share/gnome-shell/extensions` which is not a good place to save the wallpapers to. Actually, this is not just a Gentoo thing as there are packages for Gnome extensions on Arch and other Distributions as well. Some people just prefer using a package manager over any random download tool or cloning git repos.

Without an option to select a custom wallpaper directory, this extension will not really work using any package manager. I've never written any extension for Gnome but would it be possible to have an option where you could select a directory instead of hard coding it with `Self.path + '/wallpapers/';` in `wallpaperController.js`?

**Comment by ifl0w** [comment]
@r7l This should be possible. However, I am currently not actively developing this extension and it definitely would benefit from an overhaul. Changing the storage location is also a feature that should be implemented.
I opened a new issue #86 to track this feature but I do not know when I'll find the time to rework the extension.

**Comment by r7l** [comment]
Thanks.
