### ISSUE TITLE
Use different keywords

### ISSUE THREAD

**Issue by le-mon** [ifl0w/RandomWallpaperGnome3#39]
Hey there, 

wouldn't it be nice, to have different keywords so the pictures show different topics?
At the moment you can have more than word, as i pressume, but its more or less a "key combination". 

I would like to have more variety. i.e. Keywords are: [Architecture, Food, Classical Musik]

**Comment by ifl0w** [comment]
Hello,

it probably would be nice, but the API of Unsplash does not support disjunctive keywords. I'd have to make multiple requests for every keyword and then choose a picture from the responses randomly.
The UI would probably need a rework as well to support such a feature since it already is somewhat clunky.

So, I am not sure if I am going to implement such a functionality anytime soon. 

As an alternative: I just implemented the option to filter by collections a few days ago and those are disjunctive by default. So you could search for a collection of Architecture, Food and Classical Music and use those as sources.

**Comment by le-mon** [comment]
thanks for the reply. 

After writing the issue i checked the API and already realised the same as you mentioned. 

Yeah, a "workaround" would be to use collections, nice idea.

**Comment by AlexWayfer** [comment]
It's also confusing for me: we have disjunctive "Collections", separated via comma, and one (?) "Keyword", but this field can be also filled with comma-separated multiple words. Non-intuitive. And yes, there are too many collections, and list of IDs is not obvious after a while (is this 12345 Architecture or Food?).

Just my 5 cents, I'm not pushing, of course.

**Comment by ifl0w** [comment]
I agree that the interface is not very convenient. It's basically just a direct mapping of [this API endpoint](https://unsplash.com/documentation#get-a-random-photo).

Actually, I would like to rework the userinterface of this extension completely but that would take an respectable amount of time that I currently do not have. 
Probably I should set up a milestone and break down the required changes to smaller problems, so that the plans are more visible to the public.

**Comment by ifl0w** [comment]
The use case should be supported in v3.0.0 with multiple sources. You can add the same source multiple times with different topics.
