### ISSUE TITLE
The icon keeps blinking after a new wallpaper is fetched

### ISSUE THREAD

**Issue by luca-viggiani** [ifl0w/RandomWallpaperGnome3#51]
Hi, just installed new version from extensions.gnome.org.
I've disabled the hover preview as suggested to prevent crashes.
But now the icon on top bar keeps blinking "forever" after a new wallpaper is fetched. In that case I have to disable and re-enable the extension to stop it.
Cheers

**Comment by ifl0w** [comment]
Hey, disableing the hover preview only reduces the amount of crashes. It will not prevent them completely since the problem is setting the background through Gnome GJS and not the hover preview. The hover preview only does this extensivly while using it and therefore increases the probability of a crash.

The icon should only blink forever if the download is loading forever. As soon as a download failes or the wallpaper gets updated it should stop blinking. (the error feedback is currently definitly not the best ^^)
I can not observe this bug on my machine, but if it exists for more users it should be fixed as soon as possible since this sounds really anoying!

Wich source are you using, and what gnome version? Are you able to provide the logs of the extension over the period of the error? 
If I am not able to reproduce the issue, then it will be hard to find the cause.

**Comment by luca-viggiani** [comment]
Hi, in my case the icon keeps blinking even after the new wallpaper is set (so the download is completed).
I'm running gnome 3.30.1 on Arch. The extension is installed from extensions.gnome.org and today I have updated it to latest version (available on that site) and the blinking issue started fro me. `metadata.json` says `version: 14`.
How do I get logs for the extension?

**Comment by ifl0w** [comment]
I just tried it on my laptop, which is basically the same setup, and it works without problems there.

You can follow the logs of the gnome-shell with the command: `journalctl -f /usr/bin/gnome-shell`
And you can limit the output to the intentional logs of the extension with: `journalctl -f /usr/bin/gnome-shell | grep RWG`

The limited output will most likely not show the problem though.

**Comment by luca-viggiani** [comment]
In the mean time I rebooted my computer and the issue seems to be gone. Perhaps something happened during the upgrade of the extension (unload old and load the new one). BTW I'm closing this issue.
Sorry for the noise...

**Comment by ifl0w** [comment]
No problem! The usual fix for all problems. :rofl: 
Thanks for the update!
