### ISSUE TITLE
TypeError: data.user is undefined -- unsplash

### ISSUE THREAD

**Issue by drmikecrowe** [ifl0w/RandomWallpaperGnome3#53]
Cannot change wallpapers:

```
Dec 19 08:20:48 mcrowe-Virtual-Machine gnome-shell-ext[110239]: JS WARNING: [/home/mcrowe/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/sourceAdapter.js 173]: reference to undefined property "user"
Dec 19 08:20:48 mcrowe-Virtual-Machine org.gnome.Shell.desktop[96036]: RWG3 [ERROR] >> BaseAdapter :: {"error":"Unexpected response. (TypeError: data.user is undefined)"}
Dec 19 08:20:48 mcrowe-Virtual-Machine org.gnome.Shell.desktop[96036]: RWG3 [ERROR] >> WallpaperController :: Could not fetch wallpaper location.

 $ gnome-shell --version
GNOME Shell 3.28.3

```

**Comment by ifl0w** [comment]
Can you share the exact settings of the unsplash source that you are using? 
There has to be a problem with the HTTP request as the response is not as expected.

**Comment by JoergPalmer** [comment]
Having the very same effect here ...

    ... gnome-shell[26946]: RWG3 [ERROR] >> BaseAdapter :: {"error":"Unexpected response. (TypeError: data.user is undefined)"}
    ... gnome-shell[26946]: RWG3 [ERROR] >> WallpaperController :: Could not fetch wallpaper location.

My unsplash source:

Username: <my username>
Collection: my-collection
Keyword: wallpaper
Image Width: 1920
Image Height: 1080

Question: Username with or without '"@"? Both variants show the same error.

**Comment by ifl0w** [comment]
It does not matter if you specify the username with or without "@". That case is handled.

I just tried out to combine a username and a collection and it seems that in those cases the collection is ignored. I am not sure what's happening here.

Another important note is that keywords and collections should not be used at the same time since the API does not support it. https://unsplash.com/documentation#get-a-random-photo

Finally, I do not know why the requests failed for you. It could be a problem with unsplash (e.g. downtime) or the exact combination of the filters you specified. 
I suggest using as little filters at the same time as possible for the unsplash source.
