### ISSUE TITLE
Add simple URL source for images

### ISSUE THREAD

**Issue by adamplumb** [ifl0w/RandomWallpaperGnome3#67]
I found out about this GOES satelite that generates new images every 10 minutes of various parts of the globe (and the full disk).  They don't seem to have a json file available, but they do update a static URL with a new image.  So it would be great if I could just point to a URL and have it auto-refresh a new image.

The json to make this work is:
```
{
    "url": "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/1808x1808.jpg"
}
```
with a key of `$.url`.

I was able to get this to work by uploading this json file to a publically accessible web page, but it would be neat to just be able to point to the URL itself.

**Comment by ifl0w** [comment]
That is a good idea and can be implemented as an additional HTTP source, but I am not sure how useful it would be since most image URLs point to a static image.
It is far more typical to expose changing data through a JSON API, and this is the reason why I implemented the generic JSON source.

If more people are interested in such an implementation and more use cases are found, then I'll consider it for a future update.
Thank you for the suggestion!

**Comment by ifl0w** [comment]
Supported in v3.0.0
