### ISSUE TITLE
Request new wallpaper stuck on loading

### ISSUE THREAD

**Issue by murdak** [ifl0w/RandomWallpaperGnome3#98]
Ubuntu 20.04 LTS
Gnome 3.36.8

In settings window, under general tab, after clicking Request New Wallpaper, it becomes Loading but nothing happens.
Using the New Wallpaper in the taskbar menu changes the wallpaper immediately.

Wallpaper provider is reddit: EarthPorn

**Comment by ifl0w** [comment]
Hello, this problem should be solved already (#84). However, I did not release it on extensions.gnome.org yet.
So could you try installing the extension from the repository and confirm that everything is working for you? Otherwise, I'll close the issue and you'll have to wait until the update is on the extension website.

**Comment by murdak** [comment]
Fixed on latest pull. Thank you @ifl0w
