### ISSUE TITLE
Error on UnsplashAdapter

### ISSUE THREAD

**Issue by c0ki** [ifl0w/RandomWallpaperGnome3#99]
Hi,

When RandomWallpaperGnome3 request download location on Unsplah, there is an error on downloadLocation url (sourceAdapter.js, line: 166) : double *?* on query params. This error is due to link into return api already content a *?* and the adapter add *?* before clientParam... maybe the links.download_location format change on api.

To resolve this bug, i change
```
let downloadLocation = data.links.download_location + '?' + clientParam;
```
to
```
let downloadLocation = data.links.download_location + '&' + clientParam;
```

But the best solution will be to check if data.links.download_location content a *?* (and use *&*) or not (and use *?*)

**Comment by christiansayers** [comment]
Can confirm, Unsplash stopped working and the above code change fixed it for me. Thanks @c0ki

**Comment by ifl0w** [comment]
Hey. thanks for reporting and debugging! From your description, it really sounds like the returned URL from the API changed. I plan to take a closer look at it tomorrow!
However, if you are interested and sure that this is the appropriate fix you could also make a PR. Otherwise, I'll incorporate the fix myself. :)

Thanks again!

**Comment by ifl0w** [comment]
I plan to release the fixed version as soon as possible. In the meanwhile, you might want to install the app from the repository. :)
